"""create subscriptions table

Revision ID: 69b5c54db7e7
Revises: 8a7d9349f34a
Create Date: 2026-06-29 15:34:55.905220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b5c54db7e7'
down_revision: Union[str, Sequence[str], None] = '8a7d9349f34a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('subscription_token', sa.String(length=128), nullable=False),
    sa.Column('xui_client_id', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('protocol', sa.String(length=32), nullable=False),
    sa.Column('traffic_limit', sa.Integer(), nullable=False),
    sa.Column('traffic_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('xui_client_id')
    )
    op.create_index(op.f('ix_subscriptions_subscription_token'), 'subscriptions', ['subscription_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_subscription_token'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
