"""add client_email to subscriptions

Revision ID: b6ce650284cc
Revises: 92b0eb7ef66f
Create Date: 2026-06-29 17:37:41.477934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ce650284cc'
down_revision: Union[str, Sequence[str], None] = '92b0eb7ef66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('client_email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_subscriptions_client_email'), 'subscriptions', ['client_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_client_email'), table_name='subscriptions')
    op.drop_column('subscriptions', 'client_email')
    # ### end Alembic commands ###
